### ISSUE TITLE
License MIT?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [baltermia/barcodereader-imagesharp#3]
What's the license for this project? Can you clarify?

**Comment by baltermia** [comment]
I never really thought about it. Could you perhaps help me out? I'm not quite sure which one to use.

MIT sounds logical, I've used it elsewhere, but this library also depends on [Zxing.Net](https://github.com/micjahn/ZXing.Net/) which uses the [Apache License 2.0](https://github.com/micjahn/ZXing.Net/blob/master/COPYING). So it might have to be this?

**Comment by baltermia** [comment]
In addition [SixLabors.ImageSharp](https://github.com/SixLabors/ImageSharp/) uses [Apache License 2.0](https://github.com/SixLabors/ImageSharp/blob/main/LICENSE) as well.

**Comment by PrzemyslawKlys** [comment]
I've been using MIT in all my projects with 1 exception where the project my project is based on is AGPL. In that case, I used the AGPL license as well because I was not able to tell if I can use my own license or needed to keep other project licenses. I guess I should be able to license "my code" however I want - because I wrote it. Just because it's using some DLL - shouldn't matter, but I didn't wanted my "users" to get into trouble if they somehow use the DLL the wrong way. 

I have a project https://github.com/EvotecIT/OfficeIMO I also was thinking about a license - and people said I should pick MIT which allows me to change the license later on if I decide on it, expand, or dual license even.

Some things to read on: 
- https://choosealicense.com/community/
- https://soos.io/apache-vs-mit-license/

In the end, you're licensing out your code, not theirs. So if people modify your code they have to adhere to your demands, and if they want to use ImageSharp or Zxing.Net - to their demands - but they do accept their license during NuGet installation, and your license during your product installation.

**Comment by baltermia** [comment]
Okay, thanks for the clarification. I will set it to MIT.

**Comment by baltermia** [comment]
Closing with commits 36f378a2edc94bd96e511963fc648fbb2f30603c and 58b529c5646dfa5c12b5650317d90eb734eb5561.

**Comment by PrzemyslawKlys** [comment]
Is it dual licensed now?

![image](https://user-images.githubusercontent.com/15063294/174994704-cc924245-3612-418b-bf1f-9a6271340f95.png)

I see license, and license.md files.

**Comment by baltermia** [comment]
Wow that is weird! I actually went into the LICENSE.md file and edited it with the MIT template, which then just created it's own new file. I didn't expect that behavior. Great catch, thank you. It's fixed now :)
